apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyhouse-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyhouse-client
  template:
    metadata:
      labels:
        app: tinyhouse-client
    spec:
      containers:
        - name: tinyhouse-client
          image: webmakaka/tinyhouse-client-app2
          env:
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-publishable-key
                  key: STRIPE_PUBLISHABLE_KEY
            - name: STRIPE_CONNECT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: stripe-connect-client-id
                  key: STRIPE_CONNECT_CLIENT_ID
