apiVersion: skaffold/v2beta16
kind: Config
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
    - image: webmakaka/tinyhouse-client-app2
      context: ../app/client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts*'
            dest: .
    - image: webmakaka/tinyhouse-server-app2
      context: ../app/server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts*'
            dest: .
deploy:
  kubectl:
    manifests:
      - ../k8s/*
